kind: Service
apiVersion: v1
metadata:
  name: polyfea-controller
  namespace: polyfea
spec:
  ports:
  - name: webserver
    protocol: TCP
    targetPort: http
    port: 80
    nodePort: 30331
  type: NodePort